<?php

/**
 * @file
 * Geoname example form element
 */

/**
 * Implements hook_menu().
 */
function geonames_tools_menu() {
  $items['geonames/autocomplete'] = array(
    'title'   => 'Autocomplete Geonames Search',
    'page callback' => 'geonames_tools_search_autocomplete',
    'access arguments' => array('access content'),
    'type'    => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Provide JSON results of a location search for $search.
 */
function geonames_tools_search_autocomplete($search) {
  $matches = array();
  $query = array(
    'query' => $search,
    'maxrows' => 15,
    'featureclass' => array('P'),
    'featurecode' => array('PPL', 'PPLA', 'PPLG', 'PPLR', 'PPLC', 'PPLS', 'STLM'),
    'style' => 'full',
  );
  $result = geonames_query('search', $query);
  if ($result->total_results_count) {
    foreach ($result->results as $m) {
      $r  = $m['name'];
      $r .= ($m['adminname1']) ? ', ' . $m['adminname1'] : '';
      $r .= ($m['countryname']) ? ', ' . $m['countryname'] : '';
      $r .= " >> " . $m['lat'] . "," . $m['lng'];
      $matches[$r] = $r;
    }
  }
  print drupal_json_encode($matches);
  exit();
}

/**
 * Add a sample form that uses the autocomplete function provided by this
 * module.
 */
function geonames_tools_form_geonames_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['geonames_tools'] = array(
    '#type' => 'fieldset',
    '#title' => t('Geonames Tools'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 8,
  );
  $form['geonames_tools']['search'] = array(
    '#type'              => 'textfield',
    '#title'             => t('Sample Location Search'),
    '#description'       => t('Search for location'),
    '#autocomplete_path' => 'geonames/autocomplete',
  );
}
